### ISSUE TITLE
add_host functionality adds a ":" to the end of the String, causing a an exception

### ISSUE THREAD

**Issue by lbornov2** [test-kitchen/kitchen-docker#174]
Environment info
```
kitchen-docker version: 2.3.0
test-kitchen version:  1.2.1.
OS:  OSX
```

boot2docker version
```
Boot2Docker-cli version: v1.8.0
Git commit: 9a26066
```
docker version
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        Thu Oct 15 09:12:56 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```
.kitchen.yml:
```
---
driver:
  name: docker
  add_host: etcd:127.0.0.1
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>
  privileged: true
  provision_command:
    - yum install -y tar cronie crontabs sendmail

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4
  environments_path: test/environments

platforms:
- name: centos-7
  driver:
    run_command: /usr/sbin/init

suites:
  - name: default
    provisioner:
      client_rb:
        environment: dev
    run_list:
    attributes:
      kitchen: true
      ha_disabled: true
      etcd:
        server: 127.0.0.1
```

Output of kitchen converge:
```
----> Starting Kitchen (v1.4.2)
       /Users/lbornova/.chefdk/gem/ruby/2.1.0/gems/mixlib-shellout-2.2.1/lib/mixlib/shellout/unix.rb:338: warning: Insecure world writable dir /usr/local in PATH, mode 040777
-----> Creating <default-centos-7>...
       /Users/lbornova/.chefdk/gem/ruby/2.1.0/gems/mixlib-shellout-2.2.1/lib/mixlib/shellout/unix.rb:338: warning: Insecure world writable dir /usr/local in PATH, mode 040777
       invalid value "etcd:127.0.0.1:" for flag --add-host: invalid IP address in add-host: "127.0.0.1:"
       See 'docker run --help'.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '2'
---- Begin output of docker -H tcp://192.168.59.104:2376 run -d -p 22 --add-host=etcd:127.0.0.1: --privileged 9f58f5272fdf /usr/sbin/init ----
STDOUT:
STDERR: /Users/lbornova/.chefdk/gem/ruby/2.1.0/gems/mixlib-shellout-2.2.1/lib/mixlib/shellout/unix.rb:338: warning: Insecure world writable dir /usr/local in PATH, mode 040777
invalid value "etcd:127.0.0.1:" for flag --add-host: invalid IP address in add-host: "127.0.0.1:"
See 'docker run --help'.
---- End output of docker -H tcp://192.168.59.104:2376 run -d -p 22 --add-host=etcd:127.0.0.1: --privileged 9f58f5272fdf /usr/sbin/init ----
Ran docker -H tcp://192.168.59.104:2376 run -d -p 22 --add-host=etcd:127.0.0.1: --privileged 9f58f5272fdf /usr/sbin/init returned 2]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Seems like something is adding an extra ":" at the end of the add-host, which is causing the IP to be invalid.

**Comment by foxfire206** [comment]
I ran into this issue too and did a little dig through lib/kitchen/driver/docker.rb to find the following line: 
```
Array(config[:add_host]).each {|host, ip| cmd << " --add-host=#{host}:#{ip}"}
```

All other config items look to expect only one argument (per each entry), while add_host expects two. I did a quick test with this modification to my .kitchen.yml file, and everything worked as expected:
```
driver:
  name: docker
  add_host:
    - ["place.host.com","xxx.xxx.xxx.xxx"]
```
