### ISSUE TITLE
Unable to create instances

### ISSUE THREAD

**Issue by peco8** [test-kitchen/kitchen-docker#175]
I”m trying to Test Kitchen to use Docker containers for our Chefbook testing with following installed on my local machine

- test-kitchen (1.4.2)
- docker (1.8.3)
- kitchen-docker (2.3)
- docker-machine (0.4.1)

The issue is unable to create containers after deleting the first instance (which worked).
I use docker-machine to create instances, and create containers with ( kitchen create ) again, and then fails.

The error message:
<img width="804" alt="screen shot 2015-11-05 at 16 36 02" src="https://cloud.githubusercontent.com/assets/4458427/10962558/7dc1fa38-83dc-11e5-969c-c3803ce074dd.png">

I created another containers for demo ( nginx, busybox)
<img width="1145" alt="screen shot 2015-11-05 at 16 36 22" src="https://cloud.githubusercontent.com/assets/4458427/10962564/8d76b3ec-83dc-11e5-9dc3-136ad16e3383.png">

My .kitchen.yml file looks like:

```yml
---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>
  binary: /usr/local/bin/docker
  provision_command: curl -L http://www.opscode.com/chef/install.sh | bash
  dns:  
  - 8.8.8.8
  - 8.8.4.4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[homepage-test::default]
    attributes:
```

i also can’t confirm that the docker container is started, by running 
` docker ps -a `

Can anyone please suggest what might be wrong? Has anyone run into this before?

### UPDATED ###

After I got the error, and try `kitchen test`  and started the test.
I don't know how it really works. For my understanding, "Test Kitchen creates an instance of your virtual environment, for example"

So I couldn't figure out the reason why i failed with `kitchen create` but succeeded with `kitchen test`
