### ISSUE TITLE
Private Docker Registry

### ISSUE THREAD

**Issue by ghost** [test-kitchen/kitchen-docker#177]
Hey guy, I could not find any resources on the subject but can kitchen-docker work with a private docker registry?  Thanks!

**Comment by ytsarev** [comment]
short answer, yes :)
```
---
driver:
  name: docker
  image: docker-registry.example.com/image:tag
```
