### ISSUE TITLE
Prompts for password when running kitchen login

### ISSUE THREAD

**Issue by robertlabrie** [test-kitchen/kitchen-docker#226]
1.9.2 - no issue
1.11.1 - issue

when I run kitchen login I get prompted for a password

.kitchen.yml is below, and the recipe is literally: `puts "Test kitchen"`

```

---
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero

platforms:
  - name: centos-6
    driver:
      disable_upstart: false
      run_command: /sbin/init
suites:
  - name: default
    run_list:
      - recipe[breakglass::default]
    attributes:
```
