### ISSUE TITLE
Start supporting containers

### ISSUE THREAD

**Issue by blairham** [test-kitchen/kitchen-docker#239]
It would be incredibly useful if we could define supporting containers (ie databases, or prebuilt container images) that would be required for the image we are testing.

it could looks something like:
```
suites:
  - name: server
    run_list:
      - recipe[myserver::default]
    driver:
        supporting_containers:
          - postgres
            name: postgres
            environment:
              - POSTGRES_PASSWORD: password
              - POSTGRES_USER: postgres
...
```

This would allow for some pretty advanced capabilities that test-kitchen currently lacks.
