### ISSUE TITLE
Message of "Waiting for localhost 22" does not stop.

### ISSUE THREAD

**Issue by inokappa** [test-kitchen/kitchen-docker#24]
When I execute the "kitchen create": message of "Waiting for localhost 22" does not stop.I discovered that the port number of the container is not known to `test-kitchen-1.0.0.beta.4/lib/kitchen/ssh.rb`.

I wonder if it happens around only me.
Please confirm following.
#### My Environment
- Ubuntu 13.10
- lxc-docker-0.6.7
- kitchen-docker 0.10.0
- test-kitchen 1.0.0.beta.4
#### My .kitchen.yml

```

---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    username: kitchen
    password: kitchen

suites:
- name: default
  run_list: ["recipe[cookbook]"]
  attributes: {}
```
#### Step

following execute steps

```
sudo bundle exec kitchen create
```

`Waiting for localhost:22...` does not stop

```
       }]
       [kitchen::driver::docker command] END (0m0.02s)
       Waiting for localhost:22...
       Waiting for localhost:22...
```

To Press Ctrl + C stop.
#### container status

```
CONTAINER ID        IMAGE               COMMAND                CREATED              STATUS              PORTS                   NAMES
348afb81f484        8648dff97a96        /usr/sbin/sshd -D -o   About a minute ago   Up About a minute   0.0.0.0:49190->22/tcp   slate_fish
```
