### ISSUE TITLE
Support amazonlinux container

### ISSUE THREAD

**Issue by tjj9020** [test-kitchen/kitchen-docker#242]
It would be nice to support the new amazonlinux docker container.

https://hub.docker.com/_/amazonlinux/

**Comment by LevonBecker** [comment]
+1

Here's my current workaround:

https://www.bonusbits.com/wiki/HowTo:Configure_Amazon_Linux_Docker_Image_for_Test_Kitchen_in_Chef_Cookbook

**Comment by myoung34** [comment]
Any news on this?

**Comment by LevonBecker** [comment]
This works for me...

```yaml
---
verifier:
  name: inspec
  format: <%= ENV['CI'] ? 'junit' : 'cli' %>
  <% if ENV['CI'] %>
  output: "test-reports/%{platform}_%{suite}_inspec.xml"
  <% end %>

driver:
  name: docker
  use_sudo: false
  privileged: true
  forward: 80
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

platforms:
  - name: amazon-docker
    driver_config:
      image: amazonlinux:latest
      platform: rhel

suites:
  - name: default
    run_list:
      - recipe[example_serverspec_to_inspec::default]
    attributes:
```

**Comment by tristanmorgan** [comment]
T.K. will determine the image to use if you specify the name like the following.
``` yaml
platforms:
  - name: amazonlinux-2017.09
    driver_config:
      platform: rhel
```
