### ISSUE TITLE
Docker volumes are not passed to command

### ISSUE THREAD

**Issue by joestump** [test-kitchen/kitchen-docker#244]
I'm running Kitchen from a Bundle, which perhaps is causing this issue, but I can't get seem to get `kitchen-docker` to append `-v` as the docs describe. When I open `.kitchen/logs/kitchen.log` The command ran is:

```
docker -H unix:///var/run/docker.sock build -f /Users/josephstump/dev/goldstar/chef-repo/Dockerfile-kitchen20161205-14351-1q4p8vt .
```

Here's the driver output from `kitchen diagnose`:

```yaml
    driver:
      binary: docker
      build_context: true
      build_options: 
      cap_add: 
      cap_drop: 
      disable_upstart: true
      dns:
      - 8.8.8.8
      - 8.8.4.4
      image: ubuntu:16.04
      instance_name: jenkinsubuntu1604-josephstump-JoesGoldstariMaclocal-t4qs6upi
      kitchen_root: "/Users/josephstump/dev/goldstar/chef-repo"
      log_level: :info
      name: docker
      platform: ubuntu
      private_key: "/Users/josephstump/dev/goldstar/chef-repo/.kitchen/docker_id_rsa"
      privileged: false
      provision_command:
      - apt-get install traceroute apt-transport-https cpio apt-utils
      - wget -O - http://apt.goldstar.com/sources.list | sed '/dell/d' | sed '/percona/d'
        | sed 's/precise/xenial/g' | tee /etc/apt/sources.list
      - apt-key list | grep -q 63F32BB8 || wget -qO- http://apt.goldstar.com/public.gpg
        | apt-key add -
      - DEBIAN_FRONTEND=noninteractive apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-upgrade etch
      - ls -alF /mnt/etch
      - etch --gen --local /mnt/etch /etc/passwd /etc/shadow /etc/sudoers
      - curl -L https://www.opscode.com/chef/install.sh | bash
      public_key: "/Users/josephstump/dev/goldstar/chef-repo/.kitchen/docker_id_rsa.pub"
      publish_all: false
      remove_images: false
      run_command: "/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes
        -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid"
      run_options: 
      security_opt: 
      socket: unix:///var/run/docker.sock
      test_base_path: "/Users/josephstump/dev/goldstar/chef-repo/test/integration"
      tls: false
      tls_cacert: 
      tls_cert: 
      tls_key: 
      tls_verify: false
      use_cache: true
      use_sudo: false
      username: kitchen
      volume: "/Users/josephstump/dev/goldstar/etch:/mnt/etch"
      wait_for_sshd: true
```

All of the `provision_commands` run fine until it gets to needing `/mnt/etch`.
