### ISSUE TITLE
SSH service not connecting when running parallel tests with parallel test executor plugin

### ISSUE THREAD

**Issue by jshpopelka272** [test-kitchen/kitchen-docker#251]
I'm trying to do paralleled testing to speed up kitchen tests in Jenkins. 

Using the parallel test executor plugin, it seems only one of the four tests is able to establish an SSH connection. For the other three, I get an error message similar to this one:
`Failed to complete #create action: [SSH session could not be established] on mongo-rhel-7`

Below, is the code I'm trying to run:
```

 def array = ['default', 'mongo', 'api', 'ui']
     def stepsForParallel = [:]
 	for (int element = 0; element < array.size(); element++) {
 		def getArray = array.get(element)
 		def stepName = "echoing ${getArray}"
 		stepsForParallel[stepName] = transformIntoStep(getArray)
 	}
 	stepsForParallel.failFast = true
      parallel stepsForParallel
      sh '! grep failed default-rhel-7.log.xml'
 }
 
 def transformIntoStep(array) {
 	return {
 		echo "Need more time"
 		sh "kitchen test -d always ${array}-rhel-7 | tee ${array}-rhel-7.log"
 		sh "awk -f filter_junit.awk ${array}-rhel-7.log > ${array}-rhel-7.log.xml"
 		step([$class: "JUnitResultArchiver", testResults: "${array}-rhel-7.log.xml"])
 }
```

My .kitchen.yml file looks like this:

 ```
platforms:
   - name: rhel-7
     driver_config:
       image: rhel7base:latest
       platform: rhel
 suites:
   - name: default
     run_list:
       - recipe[hygieia::default]
     attributes:
   - name: mongo
     run_list:
       - recipe[hygieia::default]
       - recipe[hygieia::mongo]
     attributes:
   - name: eve
     run_list:
       - recipe[hygieia::default]
       - recipe[hygieia::eve]
     attributes:
   - name: api
     run_list:
       - recipe[hygieia::default]
       - recipe[hygieia::api]
     attributes:
   - name: ui
     run_list:
       - recipe[hygieia::default]
       - recipe[hygieia::ui]
     attributes:
```

Using kitchen-docker version: 2.6.0
Docker pipeline version: 1.9.1
