### ISSUE TITLE
SSH continually tries (and fails) to connect to container

### ISSUE THREAD

**Issue by Mierdin** [test-kitchen/kitchen-docker#254]
After successfully building the image and starting a container, I am seeing this output from kitchen:

```
       Successfully built 5901cc403a60
       6ceee57d6513d02b4ffc5816b3f3a0167e423a3375691046279e414c27acef4e
       0.0.0.0:32775
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
       Waiting for SSH service on localhost:32775, retrying in 3 seconds
```

I know that the port is accessible, in part because of `docker ps` output but also because I can telnet to the port:

```
~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                   NAMES
6ceee57d6513        5901cc403a60        "/sbin/init"        11 minutes ago      Up 11 minutes       0.0.0.0:32775->22/tcp   defaultcentos6-oswaltm-C02RF1RYFVH8-mjgnwpli
d37cddf0039f        5901cc403a60        "/sbin/init"        12 minutes ago      Up 12 minutes       0.0.0.0:32774->22/tcp   defaultcentos7-oswaltm-C02RF1RYFVH8-wau9mycw

~$ telnet localhost 32775
Trying ::1...
Connected to localhost.
Escape character is '^]'.
SSH-2.0-OpenSSH_6.6.1
```

So, I suspect it could be an auth issue perhaps, but am not sure how kitchen tries to auth to the container. Any ideas?

**Comment by coderanger** [comment]
Auth is via SSH keys configured automatically by the driver. What does your kitchen config look like?

**Comment by Mierdin** [comment]
Below is my `.kitchen.yml`. Note that the problem is only happening for the centos tests.

```
---
driver:
  name: docker
  privileged: true
  use_sudo: false

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  hosts: all
  roles_path: roles
  requirements_path: roles/mistral/requirements.yml
  ansible_verbose: true
  ansible_verbosity: 2
  # TODO: Make sure Ansible playbooks are idepotent
  idempotency_test: false

platforms:
  # Ubuntu Trusty with Upstart
  - name: ubuntu-14.04
    driver_config:
      image: stackstorm/packagingtest:trusty
      platform: ubuntu
      disable_upstart: false
      run_command: /sbin/init
  # Ubuntu Xenial with Systemd
  - name: ubuntu-16.04
    driver_config:
      image: stackstorm/packagingtest:xenial
      platform: ubuntu
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-6
    driver_config:
      dockerfile: Dockerfile
      image: stackstorm/packagingtest:centos6
      platform: rhel
      run_command: /sbin/init
  - name: centos-7
    driver_config:
      dockerfile: Dockerfile
      image: stackstorm/packagingtest:centos7
      platform: rhel
      run_command: /sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: default
```
