### ISSUE TITLE
kitchen-docker drive space usage

### ISSUE THREAD

**Issue by david-crowder** [test-kitchen/kitchen-docker#30]
I was experimenting with kitchen-docker on a rhel machine recently and ran into some issues regarding the /var/lib/docker directory. It seems that a large portion of drive space is consumed during the test kitchen run, and is not recovered afterward. Is this expected behavior? For example, drive space usage for /var during a run looks like:  

1.4G (start) -> 11G (converge) -> 7G (after destroy)

even though the base container is relatively small.

I recognize that this is probably due to the way that docker works (as multiple containers are spawned during the run), but any information on how to best manage this would be helpful. I ran a similar test on an ubuntu VM and got the same results.

current .kitchen.yml

```

---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true
  remove_images: true

platforms:
- name: centos
  driver_config:
    image: centos
    platform: rhel

suites:
- name: default
  run_list: ["recipe[jenkins_wrapper]"]
  attributes: {}
```

test-kitchen (1.1.1)
kitchen-docker (0.13.0)

Sorry if this is the wrong place to post, the readme indicated this was the preferred avenue for questions.
