### ISSUE TITLE
kitchen-docker fails when testing multiple platforms

### ISSUE THREAD

**Issue by nergdron** [test-kitchen/kitchen-docker#302]
my .kitchen.yml has the following platform config that fails when using kitchen-docker:

```
platforms:
  - name: ubuntu-16.04
  - name: ubuntu-17.10
  - name: ubuntu-18.04
```

what seems to be happening is its leaves the first container running, bound to port 22 on the docker host, so 17.10 and 18.04 fail when they get to the "start ssd" step, since they can't bind to the same port.

I suspect for this to work properly kitchen-docker should stop trying to bind to the host system on 22 and instead just use the container IP address directly. and it's also probably a good idea to stop a working container when a kitchen run is complete anyway.
