### ISSUE TITLE
Kitchen Login Fails w. Unprotected Private Key File 

### ISSUE THREAD

**Issue by darkn3rd** [test-kitchen/kitchen-docker#316]
Running `kitchen create` and `kitchen login` fails as permissions are too open.

## STEPS

```bash
$ export KITCHEN_YAML=kitchen.docker.yml
$ kitchen create
$ ls -la .kitchen/docker_id_rsa
-rw-r--r--  1 jmenchaca  staff  1679 Oct 28 23:40 .kitchen/docker_id_rsa
$ kitchen login
```

The config is the following:

```yaml
---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_verbose: true
  ansible_verbosity: <%= ENV['ANSIBLE_VERBOSITY'] || 1 %>
  ansible_diff: true
  roles_path: ../../roles
  require_chef_for_busser: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    transport:
      max_ssh_sessions: 6

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
      attributes:
        service_type: sysv
```

## EXPECTED RESULTS

Login with similar behavior as if I was using vagrant.

## ACTUAL RESULTS

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/Users/jmenchaca/area51/proj/lisa18_test_driven_infra/ansible/roles/ez_mysql/.kitchen/docker_id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/Users/jmenchaca/area51/proj/lisa18_test_driven_infra/ansible/roles/ez_mysql/.kitchen/docker_id_rsa": bad permissions
```
