### ISSUE TITLE
Option to specify an image_name for Dockerfile based Kitchen Converges

### ISSUE THREAD

**Issue by dinbtechit** [test-kitchen/kitchen-docker#317]
This is related to https://stackoverflow.com/questions/53270686/kitchen-docker-specify-image-name-for-dockerfile

It would be great to have an option to specify a `image_name` while building off a Dockerfile.

How about the variable name `image_tag_name` ??

**Sample `.kitchen.yml` file**
driver:
  name: docker
  use_sudo: false
  dockerfile: /path/to/Dockerfile
 `image_tag_name: mycompany/myapp`
  remove_images: true
  privileged: true
  run_command: /usr/sbin/init

**Comment by dinbtechit** [comment]
Actually I found a way to do it.

you can actually pass the `build_options:` and `tag:`. As shown in the code below.

.kitchen.yml (the full yml file is in the question above.)

```
platforms:
 - name: centos-7
   driver_config:
    dockerfile: ../Dockerfile
    build_options:
     tag: mycompany/myapp:latest
     rm: true
    container_name: myapp
    instance_name: myapp
```
