### ISSUE TITLE
Windows fails w. Kitchen b/c Unix Socket usage

### ISSUE THREAD

**Issue by darkn3rd** [test-kitchen/kitchen-docker#318]
Running `kitchen create` fails with Docker-for-WIndows.

## STEPS

```PowerShell
> kitchen create
```

The config is the following:

```yaml
---
driver:
  name: docker

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>

verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[ez_apache::default]
    verifier:
      inspec_tests:
        - ../../../inspec/ez_apache/test/integration
      attributes:
        service_type: sysv
    attributes:
```

## EXPECTED RESULTS

Will be able to do `kitchen create` the same way I can for Linux, or Mac w/ Docker-for-Mac.  

The plug-in should detect it is in Windows environment, and use an alternative means to communicate to Docker service.  The docker client commands work fine, as well as docker python library through docker-compose.

## ACTUAL RESULTS

The default behavior is to use the Unix socket, which well, on Windows, is not going to work very well.

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20181116-14652-1p671jw . ----
STDOUT:
STDERR: protocol not available
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20181116-14652-1p671jw . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20181116-14652-1p671jw . returned 1] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
