### ISSUE TITLE
Provide authentication for images accessed via network within platform's driver_config

### ISSUE THREAD

**Issue by dbeezt** [test-kitchen/kitchen-docker#343]
I should preface this by mentioning that I'm quite new to Kitchen and Kitchen-Docker (and Configuration Management as a whole!), so apologies if I've missed something obvious.

When configuring the test environment, the image(s) to be provisioned can have their origin specified via URL. However, if the image is located behind a level of authentication (e.g. proxy network), to my knowledge there is no method of supplying authentication information to bypass whatever layer of security there may be and retrieve the image from beyond.

I was wondering whether such a method of providing authentication existed within this plugin, or if not, whether it could develop into something related to what I've pseudo'd below?

``` 
        driver:
          name: docker

        platforms:
          - name: example
            driver_config:
               platform: os
               image: path_to_image
                 image_auth: admin:password
```
