### ISSUE TITLE
Transport does not work in Windows

### ISSUE THREAD

**Issue by nanolonny** [test-kitchen/kitchen-docker#350]
I've been able to reproduce on three different Windows systems all running Windows 10 1809.  Test Kitchen fails to transport files to docker containers.

```
c:\Users\test\chef\test-cookbook>kitchen converge
-----> Starting Kitchen (v2.3.3)
-----> Converging <default-windows>...
       Preparing files for transfer
       Installing cookbooks for Policyfile c:/Users/test/chef/test-cookbook/Policyfile.rb using `chef install`
       Installing cookbooks from lock
       Installing chocolatey-wrapper 0.1.0
       Preparing dna.json
       Exporting cookbook dependencies from Policyfile C:/Temp/default-windows-sandbox-20191023-23104-1wo3bab...
       Exported policy 'chocolatey-wrapper' to C:/Temp/default-windows-sandbox-20191023-23104-1wo3bab

       To converge this system with the exported policy, run:
         cd C:/Temp/default-windows-sandbox-20191023-23104-1wo3bab
         chef-client -z
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [Docker] Executing command on container
       **Error response from daemon: filesystem operations against a running Hyper-V container are not supported**
```

kitchen.yml file:
```

`<% # Make sure the local copy of the driver is loaded %>
<% lib = File.expand_path('../lib', __FILE__) %>
<% $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib) %>
---
driver:
  name: docker
  binary: docker.exe


provisioner:
  name: chef_zero

platforms:
- name: windows
  driver_config:
    image: mcr.microsoft.com/windows:1809
    platform: windows


transport:
  name: docker
  socket: tcp://localhost:2375

verifier:
  name: inspec

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default`
```

**Comment by nanolonny** [comment]
The docker flag --isolation=process should be run to allow the transport to work by default on W10 systems.

**Comment by jeffreycoe** [comment]
@nanolonny I'm still trying to get an environment set up to test this on my machine, but would you mind testing the code in PR #351? You'll need the following driver configuration in your kitchen.yml file:
```yaml
driver:
  name: docker
  isolation: process
```

or use the following for Hyper-V: 
```yaml
driver:
  name: docker
  isolation: hyperv
```
