### ISSUE TITLE
kitchen-docker 2.10.0 doesn't work, at least not docker-in-docker

### ISSUE THREAD

**Issue by johnjolet** [test-kitchen/kitchen-docker#366]
# Version:

[2.10.0]

# Environment: [all cookbooks and ubuntu and centos containers]

# Scenario:

[docker in docker test kitchen fails, see below]

# Steps to Reproduce:

all of a sudden, possibly starting this week or last week, docker-based test kitchen pipelines have stopped working. Getting the error: "docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage: docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects

i've recreated this manually in docker on my workstation by running the chef/chefworkstation container and manually running the steps in my pipeline. I've also repeated the same using a generic centos 7 container and installing chef workstation myself. there seems to be some disconnect between kitchen-docker gem and docker-ce-cli.
Here is what i'm doing once i launch the container (the keys redacted):
#!/bin/bash
yum -y install wget
wget https://packages.chef.io/files/stable/chef-workstation/0.17.5/el/7/chef-workstation-0.17.5-1.el7.x86_64.rpm
rpm -Uvh chef-workstation-0.17.5-1.el7.x86_64.rpm
echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile
source ~/.bash_profile
gem install kitchen-docker
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum -y install docker-ce-cli
mkdir -p /builds/tech/chef-cookbooks
if [[ ! -d ~/.chef ]];then mkdir ~/.chef;fi
echo "insert key here"|base64 -d > ~/.chef/pimco-validator.pem
echo "insert key here"|base64 -d > /tmp/s_gitchf_p.pem
echo "node_name 's_gitchf_p'" >> ~/.chef/knife.rb
echo "client_key '/tmp/s_gitchf_p.pem'" >> ~/.chef/knife.rb
echo "validation_key '~/.chef/pimco-validator.pem'" >> ~/.chef/knife.rb
echo "chef_server_url 'https://chef.core.pimcocloud.net/organizations/pimco'" >> ~/.chef/knife.rb
echo "cookbook_path [ '/builds/tech/chef-cookbooks/' ]" >> ~/.chef/knife.rb
knife ssl fetch

after that i do a docker cp to the container of my git checkout and run kitchen create.
it appears that it's never creating the child container.

# Expected Result:

[kitchen creates containers]

# Actual Result:

[no container is created, and docker inspect fails because it wants an id, and no id is provided]

NOTE: forcing gem install -v 2.9.0 fixes the issue, so it's a particular issue with 2.10.0.  may be docker-in-docker specific issue.

**Comment by jeffreycoe** [comment]
Hi @johnjolet - Can you run test kitchen with `--log_level debug` turned on and post the output of your logs? Also, can you run `kitchen diagnose` and post your output, too?

**Comment by johnjolet** [comment]
Debug didn’t show anything beyond what I posted.  You should be able to reproduce this fairly easily, given the information in the ticket.

**Comment by Val** [comment]
I get the same error in my Debian/Ubuntu docker-based test kitchen pipelines when upgrading to 2.10.0.
```
-----> Starting Test Kitchen (v2.5.1)
-----> Creating <default-debian-stretch>...
         "docker inspect" requires at least 1 argument.
         See 'docker inspect --help'.
      
         Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

         Return low-level information on Docker objects
```
Falling back to 2.9.0 fix the issue.

**Comment by crazymind1337** [comment]
Same issue here since 29.03.2020.

```
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/container_helper.rb:141:in `rescue in container_ip_address'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/container_helper.rb:136:in `container_ip_address'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container.rb:45:in `create'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container/linux.rb:32:in `create'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/driver/docker.rb:123:in `create'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `public_send'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `block in perform_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:552:in `synchronize_or_call'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:514:in `block in action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:513:in `action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `perform_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:394:in `create_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:381:in `block in transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `each'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:162:in `verify'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:191:in `block in test'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:187:in `test'
 /builds/puppet-manifests/syseleven-control/Rakefile:149:in `block (3 levels) in <top (required)>'
 /builds/puppet-manifests/syseleven-control/Rakefile:139:in `chdir'
 /builds/puppet-manifests/syseleven-control/Rakefile:139:in `block (2 levels) in <top (required)>'
 /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
 /usr/local/bin/bundle:30:in `block in <main>'
 /usr/local/bin/bundle:22:in `<main>'
 Caused by:
 Kitchen::ActionFailed: Error getting internal IP of Docker container
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/container_helper.rb:141:in `rescue in container_ip_address'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/container_helper.rb:136:in `container_ip_address'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container.rb:45:in `create'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container/linux.rb:32:in `create'
 /usr/local/bundle/gems/kitchen-docker-2.10.0/lib/kitchen/driver/docker.rb:123:in `create'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `public_send'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `block in perform_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:552:in `synchronize_or_call'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:514:in `block in action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:513:in `action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:485:in `perform_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:394:in `create_action'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:381:in `block in transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `each'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:380:in `transition_to'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:162:in `verify'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:191:in `block in test'
 /usr/local/bundle/gems/test-kitchen-2.5.2/lib/kitchen/instance.rb:187:in `test'
 /builds/puppet-manifests/syseleven-control/Rakefile:149:in `block (3 levels) in <top (required)>'
 /builds/puppet-manifests/syseleven-control/Rakefile:139:in `chdir'
 /builds/puppet-manifests/syseleven-control/Rakefile:139:in `block (2 levels) in <top (required)>'
 /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
 /usr/local/bin/bundle:30:in `block in <main>'
 /usr/local/bin/bundle:22:in `<main>'
 Caused by:
 Kitchen::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
 ---- Begin output of docker -H unix:///var/run/docker.sock inspect --format '{{ .NetworkSettings.IPAddress }}'  ----
 STDOUT: 
 STDERR: "docker inspect" requires at least 1 argument.
 See 'docker inspect --help'.
 Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]
 Return low-level information on Docker objects
 ---- End output of docker -H unix:///var/run/docker.sock inspect --format '{{ .NetworkSettings.IPAddress }}'  ----
```

**Comment by crazymind1337** [comment]
I have removed some internal config which should not be related to the error like `provisioner:`

```
driver:
  name: docker
  use_sudo: false
  ## this is true when the error appears
  use_internal_docker_network: <%= ENV['CI'] ? true : false %>
  privileged: true
  run_command: '/myinit'
  provision_command:
    - echo 'APT::Acquire::Retries 5;' > /etc/apt/apt.conf.d/80-acquire-retries
    - apt-get update
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

transport:
  name: speedy_ssh

verifier:
  name: inspec

##
## here we set some internal puppet stuff to prepare the tests
## this should not be important for the error
##
# provisioner:
#   <some internal provisioner stuff>

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: <internal images based on ubuntu:14.04>
  - name: ubuntu-16.04
    driver_config:
      image: <internal images based on ubuntu:16.04>
  - name: ubuntu-18.04
    driver_config:
      image: <internal images based on ubuntu:18.04>
  - name: ubuntu-20.04
    driver_config:
      image: <internal images based on ubuntu:20.04>
```
