### ISSUE TITLE
We can running the test without using ssh

### ISSUE THREAD

**Issue by marcy-terui** [test-kitchen/kitchen-docker#96]
Thank you for new version release the other day.

We had better not use ssh on Docker container.
See also http://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/

And we have some issues like #40 #81

So, I have an idea to solve them.
And the idea has been implemented on this driver plugin that made from scratch.
https://github.com/marcy-terui/kitchen-docker_cli

I started to make the plugin because it was thought to have stopped development.
But, the mainstream of kitchen-docker has resumed development.
And I have welcome it.

@portertech 
If you want, I 'm going to make and send some PRs.
But, they become big changes.
Therefore, there are some possibilities that become unstable.
So, I want to hear what you think.

**Comment by portertech** [comment]
Kitchen is using Docker as an API to/for Linux containers, I do not see this as an anti-pattern. Many cookbooks are installing/configuring a collection of services, managing machines. Using SSH supports the common TK experience, `kitchen login`, etc. I'll check out kitchen-docker_cli to see how you're using docker exec :-)

**Comment by marcy-terui** [comment]
Using SSH on Kitchen that is not anti-pattern. I think so too.
But, I think that is important to keep the state of the base image.

Please say me if you need cooperation when you see my usage :smile:

**Comment by jake-minted** [comment]
@portertech where I would see the main benefit for this, is when I'm testing cookbooks/manifests that start upstart services. SSH does not work as a valid replacement for Upstart, and using docker images that enable upstart won't work via the current SSH experience.

I think we are operating at a rare use-case for docker images, and attempting to use them as lightweight VM's inside test-kitchen. Some of our test roles require starting multiple upstart jobs. Like, Sensu for instance. It is currently impossible to test our convergence of our sensu role, as the sensu service depends on Upstart running in order to start. 

Unless we are doing something wrong in our CI pipeline, or we want to run our CI Test Slave on a bare metal server, we will need to run TK tests from a docker or lxc driver in our cloud provider.

**Comment by ysgard** [comment]
Offering only SSH access can be a problem.  As an example, consider test-kitchen suites running with docker on CircleCI, which offers its docker interface through an encrypted URL that changes with each environment setup.  In this environment kitchen fails everytime because it can't connect to the SSH socket of the test container.  Using the native `docker exec` and `docker cp` would circumvent this issue.

**Comment by coderanger** [comment]
This is planned for the future, though for context `docker exec` didn't exist when this ticket was filed :)

**Comment by hurricanehrndz** [comment]
Any update on this?

**Comment by coderanger** [comment]
@hurricanehrndz Nope, other than that you should check out `kitchen-dokken` if this is a priority.

**Comment by coderanger** [comment]
Going to close this since while it is on my long-term roadmap, it's not in any specific planning.

**Comment by rgarrigue** [comment]
Hey, just wanted to know if this is on the roadmap nowadays ? Using SSH testing over docker feels unclean, and it's enforcing some weird stuff. For example I had to remove systemd ssh service file to rely on sysV init script otherwise kitchen couldn't login, whenever I've to test systemd services

```yaml
---
driver:
  name: docker
  use_sudo: false
  provision_command:
    - rm /lib/systemd/system/ssh.service
  run_command: /bin/systemd
  privileged: true
  volume:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
```

Meanwhile on verifier side, I just don't use SSH at all because docker backend is native for testinfra

```
verifier:
  name: shell
  remote_exec: false
  command: pytest --junitxml=test/${KITCHEN_INSTANCE}_test_report.xml --html=test/${KITCHEN_INSTANCE}_test_report.html --self-contained-html --color=yes --host="docker://root@${KITCHEN_CONTAINER_ID}" "test/integration/"
```

On my user side, I feel like I just miss a `transport: name: docker` to be good to go
